### ISSUE TITLE
Issue running evo_thermal.py

### ISSUE THREAD

**Issue by antoineTK** [Terabee/teraranger#42]
Hi guys,

I am running ROS melodic on ubuntu 18.04, I have successfully built latest package from source.

This is the error I get when trying to use evo_termal.py

`rosrun teraranger evo_thermal.py _portname:=/dev/ttyACM1
[INFO] [1652363849.175426]: Starting sensor output...
[INFO] [1652363849.183349]: Sensor output started successfully
Traceback (most recent call last):
  File "/home/uha/ROS/uha_ws/src/teraranger/scripts/evo_thermal.py", line 340, in <module>
    evo_thermal.run()
  File "/home/uha/ROS/uha_ws/src/teraranger/scripts/evo_thermal.py", line 328, in run
    thermal_image = self.auto_scaling(temp_array)
  File "/home/uha/ROS/uha_ws/src/teraranger/scripts/evo_thermal.py", line 178, in auto_scaling
    frame = cv2.applyColorMap(frame, self.selected_cmap)
TypeError: only size-1 arrays can be converted to Python scalars`

If I comment line 178 it works fine and I can see the image, but I am getting a grayscale image.

Thanks in advance for the support

**Comment by pl-kabaradjian** [comment]
Hello @antoineTK ,

From what I see it seems like it comes from the loading of custom colormaps. Do you encounter the same issue with built-in OpenCV colormaps (such as HOT and JET) ?

**Comment by antoineTK** [comment]
Hello, thanks for the support

I am not sure what you mean by using HOT and JET colormap?

**Comment by pl-kabaradjian** [comment]
I meant forcing the colormap selection or overriding the colormap list directly by replacing:
`cv2.applyColorMap(frame, self.selected_cmap) `
by
`cv2.applyColorMap(frame, cv2.COLORMAP_JET)`

If this doesn't solve the issue it might be a deeper issue on how colormaps are applied in this particular version of OpenCV. In that case, maybe trying other versions of OpenCV might do the trick.
